Add widgets for custom charts and jupyterlite notebooks
gristlabs/grist-widget pull request #99
Opened 2023-10-04 12:16 UTC by alexmojaki

2023-10-17 04:55 UTC, paulfitz commented on chart/package.json
> +      "name": "Chart",
A more specific name would be better.

2023-10-17 04:59 UTC, paulfitz requested changes
This approach worries me, and changes how the widget collection works in ways that could be hard to step back from. I'd rather have someone look seriously at alternatives before committing. Placing this on hold, since use of these widgets by URL is enough for now.

2023-10-17 04:59 UTC, paulfitz commented on chart/package.json
> +      "name": "Chart",
A more specific name would be better.

2023-10-17 04:59 UTC, paulfitz commented on jupyterlite/package.json
> +      "name": "Chart",
The name is out of sync

2023-10-18 12:34 UTC, berhalak commented
How about small mental model shift. Lets treat this github repository as a package repository (like npm), so it contains all prebuilt artifacts (js files). And in the chart and jupiter repository, you would just add a github action that will build your project and create a pull request for this one, with everything built already and configured properly?
So you will use it (this repo) as a hosting provider for your widgets, and all the source code and tests and all the machinery will still sit in your repository.

2023-10-26 21:34 UTC, paulfitz approved these changes
Thanks @alexmojaki !

2023-10-26 21:37 UTC, merged